GET HTTP://localhost:8080/apicrud/clientes

###

GET HTTP://localhost:8080/apicrud/clientes/2

###

POST HTTP://localhost:8080/apicrud/clientes
Content-Type: application/json

{
    "descricao": "Bruno",
    "telefone": "992049499"
}

###

PUT HTTP://localhost:8080/apicrud/clientes/1
Content-Type: application/json

{
    "descricao": "Bruno da Silva",
    "telefone": "24525777"
}

###

DELETE HTTP://localhost:8080/apicrud/clientes/1