GET HTTP://localhost:8080/apicrud/produtos

###

GET HTTP://localhost:8080/apicrud/produtos/2

###

POST HTTP://localhost:8080/apicrud/produtos
Content-Type: application/json

{
    "categoria": "Fármaco",
    "dataDeValidade": "2023-12-18T00:00:00",
    "descricao": "Dorflex",
    "valor": 13.50
}

###

PUT HTTP://localhost:8080/apicrud/produtos/2
Content-Type: application/json

{
    "categoria": "Fármaco",
    "dataDeValidade": "2023-12-25T00:00:00",
    "descricao": "Dorflex",
    "valor": 15.50
}

###

DELETE HTTP://localhost:8080/apicrud/produtos/1